version: "3.5"

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "users"
    volumes:
      - project:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - users
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    image: users:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASESERVER_PORT: "5432"
    depends_on:
      - postgres
    networks:
      - users
networks:
  users:
    name: network_name
volumes:
  project:
    driver: local
  pgadmin-data:
    driver: local