spring:
  application:
    name: users
  r2dbc:
    url: ${DATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}
  flyway:
    baseline-on-migrate: true
    user: ${USERNAME}
    password: ${PASSWORD}
    schemas: schema
    url: ${DATABASE}
    locations: classpath:sql-scripts
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka
